### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by mkoivuporras** [wyolum/TouchSelfie#11]
I just tried to install this with the instructions I found from makezine.com. 

First, I also have the login issues like some other peoples too.

Google Username:*my_gmail_id@gmail.com
App Specific Password
/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access ./credentials.dat: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
could not login to Google, check .credential file
   ('Error opening file', './OpenSelfie.json', 'No such file or directory', 2)

OpenSelfie.json file is missing

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1545, in __call__
    return self.func(*args)
  File "/home/pi/git/TouchSelfie/scripts/custom.py", line 271, in launch_album_select
    self.albums = listalbums.getAlbums(" **NOTE: THIS HAD HARD CODED SOME KEVIN'S GMAIL")
  File "/home/pi/git/TouchSelfie/scripts/listalbums.py", line 127, in getAlbums
    gd_client = OAuth2Login(client_secrets, credential_store, email)
  File "/home/pi/git/TouchSelfie/scripts/credentials.py", line 21, in OAuth2Login
    flow = flow_from_clientsecrets(client_secrets, scope=scope, redirect_uri='urn:ietf:wg:oauth:2.0:oob')
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/clientsecrets.py", line 125, in _loadfile
    exc.strerror, exc.errno)
InvalidClientSecretsError: ('Error opening file', './OpenSelfie.json', 'No such file or directory', 2)

Again OpenSelfie.json missing

**Comment by wyojustin** [comment]
Sorry to hear about your troubles.  The interface keeps changing underneath us.  We are not working on this right now, so you best bet is to wade through google searches.  
Justin

**Comment by bderstine** [comment]
@mkoivuporras follow the instructions on makezine more closely...

"Once it’s completed downloading, rename the file OpenSelfie.json (Figure I), then drag and drop it into the /home/pi/git/TouchSelfie/scripts directory."
